/**
 * documentExporter.ts
 * Generates and downloads downloadable PDF documents, PPT presentations,
 * and PNG/JPG image files directly from Machi AI.
 */

// Generate & Download PDF Document
export function downloadPdfDocument(title: string, content: string) {
  const cleanTitle = title.trim() || 'Machi_AI_Document';
  
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${cleanTitle}</title>
  <style>
    @page { size: A4; margin: 20mm; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #111827;
      line-height: 1.6;
      padding: 30px;
    }
    .header {
      border-bottom: 2px solid #0284c7;
      padding-bottom: 12px;
      margin-bottom: 24px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .header h1 {
      font-size: 24px;
      color: #0369a1;
      margin: 0;
    }
    .header .subtitle {
      font-size: 11px;
      color: #6b7280;
    }
    .content {
      font-size: 14px;
      white-space: pre-wrap;
    }
    pre {
      background: #f3f4f6;
      padding: 12px;
      border-radius: 8px;
      font-family: monospace;
      font-size: 12px;
    }
    .footer {
      margin-top: 40px;
      border-top: 1px solid #e5e7eb;
      padding-top: 12px;
      font-size: 10px;
      color: #9ca3af;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${cleanTitle}</h1>
      <div class="subtitle">Generated by Machi AI • Developer Jaison Kumar J</div>
    </div>
  </div>
  <div class="content">${content.replace(/```[\s\S]*?```/g, (code) => `<pre>${code.slice(3, -3)}</pre>`)}</div>
  <div class="footer">
    Created with Machi AI • Kanniyakumari District, Tamil Nadu, India
  </div>
  <script>
    window.onload = function() {
      window.print();
    };
  </script>
</body>
</html>
  `;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (!win) {
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cleanTitle.replace(/\s+/g, '_')}.html`;
    a.click();
  }
}

// Generate & Download PPT PowerPoint Presentation
export function downloadPptPresentation(title: string, slidesContent: string) {
  const cleanTitle = title.trim() || 'Machi_AI_Presentation';

  // Parse slides separated by --- or Slide headers
  const rawSlides = slidesContent.split(/---|\n(?=Slide \d+:)/i).filter((s) => s.trim().length > 0);
  
  const slidesHtml = rawSlides.map((slide, idx) => {
    const lines = slide.trim().split('\n');
    const slideTitle = lines[0].replace(/^#+|Slide \d+:/i, '').trim() || `Slide ${idx + 1}`;
    const bodyLines = lines.slice(1).join('\n');

    return `
      <div class="slide">
        <div class="slide-header">
          <h2>${slideTitle}</h2>
          <span class="slide-num">Slide ${idx + 1} / ${rawSlides.length}</span>
        </div>
        <div class="slide-body">
          ${bodyLines.split('\n').map((l) => `<p>${l.trim()}</p>`).join('')}
        </div>
        <div class="slide-footer">Machi AI Presentation • Jaison Kumar J</div>
      </div>
    `;
  }).join('');

  const fullPresentationHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${cleanTitle}</title>
  <style>
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      background: #09090b;
      color: #ffffff;
      padding: 40px;
      margin: 0;
    }
    .presentation-title {
      text-align: center;
      margin-bottom: 40px;
    }
    .presentation-title h1 {
      font-size: 32px;
      color: #38bdf8;
      margin-bottom: 8px;
    }
    .slide {
      background: #18181b;
      border: 1px solid #27272a;
      border-radius: 20px;
      padding: 32px;
      margin-bottom: 30px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.5);
      page-break-after: always;
      min-height: 400px;
      display: flex;
      flex-direction: column;
    }
    .slide-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 2px solid #0284c7;
      padding-bottom: 12px;
      margin-bottom: 20px;
    }
    .slide-header h2 {
      font-size: 22px;
      color: #f0f9ff;
      margin: 0;
    }
    .slide-num {
      font-size: 12px;
      color: #38bdf8;
      background: #0c4a6e;
      padding: 4px 10px;
      border-radius: 12px;
    }
    .slide-body {
      flex: 1;
      font-size: 16px;
      line-height: 1.8;
      color: #d1d5db;
    }
    .slide-footer {
      margin-top: 20px;
      font-size: 11px;
      color: #6b7280;
      text-align: right;
    }
  </style>
</head>
<body>
  <div class="presentation-title">
    <h1>${cleanTitle}</h1>
    <p style="color:#9ca3af; font-size:14px;">Machi AI Slide Deck • Created by Jaison Kumar J</p>
  </div>
  ${slidesHtml}
</body>
</html>
  `;

  const blob = new Blob([fullPresentationHtml], { type: 'application/vnd.ms-powerpoint' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${cleanTitle.replace(/\s+/g, '_')}_Presentation.ppt`;
  a.click();
}

// Download AI Image in PNG or JPG Format
export async function downloadImageFormat(imageUrl: string, format: 'png' | 'jpg') {
  try {
    const res = await fetch(imageUrl);
    const blob = await res.blob();

    const img = new Image();
    img.crossOrigin = 'anonymous';
    const objectUrl = URL.createObjectURL(blob);

    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width || 1024;
      canvas.height = img.height || 1024;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(img, 0, 0);
        const mimeType = format === 'png' ? 'image/png' : 'image/jpeg';
        const dataUrl = canvas.toDataURL(mimeType, 0.95);
        const a = document.createElement('a');
        a.href = dataUrl;
        a.download = `machi-ai-artwork-${Date.now()}.${format}`;
        a.click();
      }
      URL.revokeObjectURL(objectUrl);
    };
    img.src = objectUrl;
  } catch {
    // Direct fallback download link if canvas CORS is restricted
    const a = document.createElement('a');
    a.href = imageUrl;
    a.target = '_blank';
    a.download = `machi-ai-artwork-${Date.now()}.${format}`;
    a.click();
  }
}
